const API='/api/v1';
const money=n=>'₹'+(Number(n||0)/100).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2});
const fmt=n=>Number(n||0).toLocaleString('en-IN');
const kpis=[['Total cost','total_cost','primary','Net operating cost'],['Refill cost','refill_cost','','Shelf replenishment'],['Online pull cost','online_pull_cost','','Warehouse fulfilment'],['Lost revenue','lost_revenue','loss','Unserved walk-in demand'],['Gross revenue','gross_revenue','','Captured sales'],['Best baseline','base_total','baseline','Cheaper of both policies'],['Shelf-first baseline','base_shelf','','All online from shelf'],['Inventory-only baseline','base_inventory','','All online from warehouse'],['Savings vs baseline','savings','','Baseline minus actual'],['Refill count','refill_count','','Shelf reset events'],['Units lost','units_lost','','Walk-in units unavailable']];
const state={day:null,summary:null,history:[],feed:[],offset:0,historical:false,sort:false,search:'',points:[]};
const kp=document.querySelector('#kpis');kp.innerHTML=kpis.map(([label,key,cls,foot])=>`<div class="kpi ${cls}"><div class="kpi-label">${label}</div><div class="kpi-value" id="k-${key}" data-testid="kpi-${key.replace('base_total','baseline-cost').replace('base_shelf','baseline-shelf-first').replace('base_inventory','baseline-inventory-only').replace('total_cost','total-cost').replace('refill_cost','refill-cost').replace('online_pull_cost','online-pull-cost').replace('lost_revenue','lost-revenue').replace('gross_revenue','gross-revenue').replace('savings','savings').replace('refill_count','refill-count').replace('units_lost','units-lost')} data-value="0">${key.includes('count')||key==='units_lost'?'0':'₹0.00'}</div><div class="kpi-foot">${foot}</div></div>`).join('');
async function get(path){const r=await fetch(API+path);if(!r.ok)throw Error('API '+r.status);return r.json()}
function setMetric(key,value,isMoney=true){const e=document.querySelector('#k-'+key);if(!e)return;e.dataset.value=String(value||0);e.textContent=isMoney?money(value):fmt(value)}
function renderSummary(s){state.summary=s;for(const i of s.items||[])if(i.name)names[i.item_id]=i.name;document.querySelector('#day-id').textContent=s.day_id;document.querySelector('#run-status').textContent=s.status;const pct=s.events_total?Math.floor(100*s.events_processed/s.events_total):0;document.querySelector('#progress').dataset.value=pct;document.querySelector('#progress-text').textContent=pct+'%';document.querySelector('#progress-bar').style.width=pct+'%';const t=s.totals,b=s.baseline;[['total_cost',t.total_cost],['refill_cost',t.refill_cost],['online_pull_cost',t.online_pull_cost],['lost_revenue',t.lost_revenue],['gross_revenue',t.gross_revenue],['base_total',b.total_cost],['base_shelf',b.shelf_first_cost],['base_inventory',b.inventory_only_cost],['savings',s.savings_vs_baseline]].forEach(([k,v])=>setMetric(k,v));[['refill_count',t.refill_count],['units_lost',t.units_lost]].forEach(([k,v])=>setMetric(k,v,false));state.points=Array.isArray(s.cost_points)?s.cost_points.map(v=>({p:s.events_total?100*v.seq/s.events_total:0,c:v.total_cost,b:v.baseline_cost})):state.points.concat([{p:pct,c:t.total_cost,b:s.baseline_progress_total_cost??0}]).slice(-500);drawChart();renderItems(s.items||[])}
function renderItems(items){const query=state.search.toLowerCase();let rows=items.filter(i=>i.item_id.toLowerCase().includes(query)||itemName(i.item_id).toLowerCase().includes(query));if(state.sort)rows.sort((a,b)=>b.lost_revenue-a.lost_revenue);document.querySelector('#item-count').textContent=`${rows.length} items`;document.querySelector('#item-rows').innerHTML=rows.map(i=>`<tr data-testid="item-row-${esc(i.item_id)}"><td class="item-name">${esc(itemName(i.item_id))}<small>${esc(i.item_id)}</small></td><td class="num" data-testid="item-shelf-${esc(i.item_id)}" data-value="${i.shelf_qty}">${fmt(i.shelf_qty)}</td><td class="num" data-testid="item-lost-${esc(i.item_id)}" data-value="${i.lost_revenue}">${money(i.lost_revenue)}</td><td class="num" data-testid="item-refills-${esc(i.item_id)}" data-value="${i.refill_count}">${fmt(i.refill_count)}</td><td class="num" data-testid="item-pulled-${esc(i.item_id)}" data-value="${i.units_pulled}">${fmt(i.units_pulled)}</td></tr>`).join('')}
let names={};function itemName(id){return names[id]||id}function esc(x){return String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function renderHistory(days){state.history=days;document.querySelector('#history-count').textContent=`${days.length} days`;document.querySelector('#history-rows').innerHTML=days.length?days.map(d=>`<tr data-testid="history-row-${esc(d.day_id)}" data-day="${esc(d.day_id)}"><td>${esc(d.day_id)}</td><td data-testid="history-cost-${esc(d.day_id)}" data-value="${d.total_cost}">${money(d.total_cost)}</td><td data-testid="history-lost-${esc(d.day_id)}" data-value="${d.lost_revenue}">${money(d.lost_revenue)}</td><td data-testid="history-savings-${esc(d.day_id)}" data-value="${d.savings_vs_baseline}">${money(d.savings_vs_baseline)}</td></tr>`).join(''):'<tr><td colspan="4" class="empty">No simulated days yet.</td></tr>';document.querySelectorAll('#history-rows tr[data-day]').forEach(r=>r.onclick=()=>selectDay(r.dataset.day))}
function renderFeed(records){state.feed=records;const box=document.querySelector('#event-feed');box.innerHTML=records.length?records.slice().reverse().map(x=>{const e=x.event,route=(x.response.lines||[]).map(l=>`${esc(l.item_id)} shelf ${l.from_shelf}`).join(' · ');return `<div class="feed-row"><span class="seq">#${e.seq}</span><span class="type ${e.type}">${e.type==='walk_in'?'Walk-in':'Online'}</span><span class="order">${esc(e.order_id)} · ${e.lines.length} lines</span><span class="lines">${route||e.lines.map(l=>esc(l.item_id)).join(', ')}</span></div>`}).join(''):'<div class="empty">Events will appear here during replay.</div>';document.querySelector('#feed-count').textContent=`${records.length} events`;box.scrollTop=0}
async function refreshFeed(){if(!state.day)return;const s=state.summary;if(!s)return;let offset=state.historical?state.offset:Math.max(0,s.events_processed-50);const data=await get(`/day/${encodeURIComponent(state.day)}/events?offset=${offset}&limit=50`);renderFeed(data.events);document.querySelector('#feed-page').textContent=`${offset+1}–${offset+data.events.length} of ${s.events_processed}`;document.querySelector('#older').disabled=offset<=0;document.querySelector('#newer').disabled=offset+50>=s.events_processed}
async function selectDay(id){state.day=id;state.historical=true;state.offset=0;state.points=[];const s=await get(`/day/${encodeURIComponent(id)}/summary`);state.offset=Math.max(0,s.events_processed-50);renderSummary(s);await refreshFeed();document.querySelector('#connection').textContent='Historical view';await refreshHistory()}
async function refreshHistory(){try{renderHistory(await get('/days'))}catch(e){}}
function drawChart(){const canvas=document.querySelector('#cost-chart'),ctx=canvas.getContext('2d'),dpr=window.devicePixelRatio||1,w=canvas.clientWidth,h=canvas.clientHeight;canvas.width=w*dpr;canvas.height=h*dpr;ctx.scale(dpr,dpr);ctx.clearRect(0,0,w,h);const pad={l:48,r:12,t:14,b:27},cw=w-pad.l-pad.r,ch=h-pad.t-pad.b,pts=state.points;if(!pts.length){ctx.fillStyle='#a1aca6';ctx.font='12px DM Sans';ctx.fillText('Waiting for replay data',pad.l+8,h/2);return}const max=Math.max(1,...pts.map(x=>Math.max(x.c,x.b)));ctx.font='10px DM Sans';ctx.textAlign='right';for(let i=0;i<=4;i++){let y=pad.t+ch*i/4;ctx.strokeStyle='#edf0ee';ctx.beginPath();ctx.moveTo(pad.l,y);ctx.lineTo(w-pad.r,y);ctx.stroke();ctx.fillStyle='#8a9790';ctx.fillText(money(max*(1-i/4)),pad.l-7,y+3)}function line(key,color){ctx.beginPath();ctx.strokeStyle=color;ctx.lineWidth=2;pts.forEach((v,i)=>{let x=pad.l+(pts.length===1?0:i/(pts.length-1))*cw,y=pad.t+ch-(v[key]/max)*ch;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()}line('b','#c1c9c5');line('c','#147d61');ctx.textAlign='left';ctx.fillStyle='#8a9790';ctx.fillText('Event progress',pad.l,h-5)}
document.querySelector('#item-search').addEventListener('input',e=>{state.search=e.target.value;renderItems(state.summary?.items||[])});document.querySelector('#sort-lost').onclick=()=>{state.sort=!state.sort;renderItems(state.summary?.items||[])};
document.querySelector('#older').onclick=async()=>{state.offset=Math.max(0,state.offset-50);await refreshFeed()};document.querySelector('#newer').onclick=async()=>{state.offset+=50;await refreshFeed()};window.addEventListener('resize',drawChart);
async function poll(){try{const days=await get('/days');renderHistory(days);if(!state.historical){if(days.length&&state.day!==days[0].day_id){state.day=days[0].day_id;state.points=[]}if(state.day){const actual=await get(`/day/${encodeURIComponent(state.day)}/summary`);renderSummary(actual);await refreshFeed()}}document.querySelector('#connection').textContent='Data loaded';document.querySelector('#connection').style.color='#147d61'}catch(e){document.querySelector('#connection').textContent='Starting data service…';document.querySelector('#connection').style.color='#bf675d'}setTimeout(poll,1000)}
async function init(){try{const data=await get('/days');renderHistory(data);if(data.length){state.day=data[0].day_id;const row=await get(`/day/${encodeURIComponent(state.day)}/summary`);for(const i of row.items||[])names[i.item_id]=i.name||i.item_id;renderSummary(row);await refreshFeed()}document.querySelector('#connection').textContent='Data loaded';poll()}catch(e){document.querySelector('#connection').textContent='Loading supplied sample data…';setTimeout(init,1200)}}init();

// Read the organiser's CSV format, including quoted names and escaped quotes.
function parseItemsCsv(text){
  const rows=[];let row=[],field='',quoted=false;
  for(let i=0;i<text.length;i++){const c=text[i];if(quoted){if(c==='"'&&text[i+1]==='"'){field+='"';i++}else if(c==='"')quoted=false;else field+=c}else if(c==='"'){quoted=true}else if(c===','){row.push(field);field=''}else if(c==='\n'){row.push(field);rows.push(row);row=[];field=''}else if(c!=='\r'){field+=c}}
  if(quoted)throw Error('The catalog CSV contains an unfinished quoted field.');if(field!==''||row.length){row.push(field);rows.push(row)}
  if(!rows.length)throw Error('The catalog CSV is empty.');const headers=rows.shift().map((v,i)=>i===0?v.replace(/^\uFEFF/,'').trim():v.trim());
  const required=['item_id','name','category','unit_price_paise','initial_shelf_qty','refill_cost_per_unit_paise','online_pull_cost_per_unit_paise'];const missing=required.filter(h=>!headers.includes(h));if(missing.length)throw Error(`Catalog is missing columns: ${missing.join(', ')}.`);
  return rows.filter(r=>r.some(v=>v.trim())).map((r,index)=>{const item=Object.fromEntries(headers.map((h,i)=>[h,(r[i]||'').trim()]));for(const key of required.slice(3)){item[key]=Number(item[key]);if(!Number.isFinite(item[key])||!Number.isInteger(item[key])||item[key]<0)throw Error(`Invalid ${key} on catalog row ${index+2}.`)}if(!item.item_id||!item.name)throw Error(`Missing item ID or name on catalog row ${index+2}.`);return item});
}
const itemsFile=document.querySelector('#items-file'),dayFile=document.querySelector('#day-file'),loadReplay=document.querySelector('#load-replay'),uploadStatus=document.querySelector('#upload-status');
function updateUploadButton(){loadReplay.disabled=!(itemsFile.files.length&&dayFile.files.length)}
itemsFile.addEventListener('change',updateUploadButton);dayFile.addEventListener('change',updateUploadButton);
loadReplay.addEventListener('click',async()=>{
  loadReplay.disabled=true;itemsFile.disabled=true;dayFile.disabled=true;uploadStatus.classList.remove('error');
  try{
    uploadStatus.textContent='Reading and validating files…';const [csvText,dayText]=await Promise.all([itemsFile.files[0].text(),dayFile.files[0].text()]);const items=parseItemsCsv(csvText);let day;try{day=JSON.parse(dayText)}catch{throw Error('The day file is not valid JSON.')}
    if(!day||typeof day.day_id!=='string'||!Array.isArray(day.events))throw Error('Day JSON must contain a day_id and an events array.');if(!items.length)throw Error('The catalog has no item rows.');
    const loaded=await fetch(API+'/day/load',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({day_id:day.day_id,items,events:day.events})});const loadText=await loaded.text();let loadResult={};try{loadResult=JSON.parse(loadText)}catch{throw Error(`The server rejected the upload (HTTP ${loaded.status}). Check that Docker is running and the day JSON is within the upload limit.`)}if(!loaded.ok)throw Error(loadResult.message||loadResult.error||`Load failed (${loaded.status}).`);
    state.day=day.day_id;state.historical=false;state.offset=0;state.points=[];names=Object.fromEntries(items.map(i=>[i.item_id,i.name]));uploadStatus.textContent=`Scenario loaded. Replaying ${day.events.length.toLocaleString('en-IN')} events…`;document.querySelector('#connection').textContent='Replaying';
    const initial=await get(`/day/${encodeURIComponent(state.day)}/summary`);renderSummary(initial);renderFeed([]);await refreshHistory();
    const batchSize=100;
    for(let index=0;index<day.events.length;index+=batchSize){
      const batch=day.events.slice(index,index+batchSize);const response=await fetch(API+'/day/events/batch',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({events:batch})});if(!response.ok){let detail={};try{detail=await response.json()}catch{}throw Error(`Replay failed at event ${index+1}: ${detail.message||detail.error||`HTTP ${response.status}`}.`)}
      const completed=index+batch.length;uploadStatus.textContent=`Replaying events: ${completed.toLocaleString('en-IN')} / ${day.events.length.toLocaleString('en-IN')}`;const s=await get(`/day/${encodeURIComponent(state.day)}/summary`);renderSummary(s);await refreshFeed()
    }
    const final=await get(`/day/${encodeURIComponent(state.day)}/summary`);renderSummary(final);await refreshFeed();await refreshHistory();uploadStatus.textContent=`Completed: ${final.events_processed.toLocaleString('en-IN')} events for ${final.day_id}.`;document.querySelector('#connection').textContent='Connected';
  }catch(error){uploadStatus.textContent=error.message||'Could not load these files.';uploadStatus.classList.add('error')}
  finally{itemsFile.disabled=false;dayFile.disabled=false;updateUploadButton()}
});
